---
- hosts: centos
  become:
    true
  become_method:
    su
  become_user:
    root
  roles:
   - web

- hosts: ubuntu
  become:
    true
  become_method:
    sudo
  become_user:
    root
  roles:
   - web
